/*
 * Mercedes-Benz AG Programming Challenge
 *
 * - Implement the specified REST Endpoint - Protect the API with BasicAuth - Use Docker to run your application - Use one of the following languages&#58; Go, Java, Python, C++ - Automate the infrastructure rollout - Use an external service to determine the city name for depature and destination - Upload your solution to a private GitHub repository - Provide a link to the secured hosted instance of your solution - Provide the following files together with your code&#58;   * Dockerfile   * Build-Script   * Deployment-Script   * Kubernetes deployment YAML (if Kubernetes is used)   * Infrastructure automation scripts   * README.md with documentation how to deploy the infrastructure and the application
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VehiclePushDataPoint struct {

	// unix timestamp
	Timestamp int64 `json:"timestamp,string,omitempty"`

	// odometer value for a given time
	Odometer int32 `json:"odometer,string,omitempty"`

	// fuel level for a given time in percent
	FuelLevel int32 `json:"fuelLevel,string,omitempty"`

	// latitude position for a given time
	PositionLat float32 `json:"positionLat,string,omitempty"`

	// longitude position for a given time
	PositionLong float32 `json:"positionLong,string,omitempty"`
}
